### ISSUE TITLE
Issue with ec2metadata output on aws ec2 instance sles 15 sp5

### ISSUE THREAD

**Issue by sdrivas** [SUSE/susecloud-repocheck#59]
2024-05-17 14:50:33,818 WARNING: There was 1 problem.
2024-05-17 14:50:33,818 INFO: Collecting debug data. Please wait 1-2 minutes maybe longer, depending on machine type.
Traceback (most recent call last):
  File "/usr/bin/ec2metadata", line 129, in <module>
    main()
  File "/usr/bin/ec2metadata", line 79, in main
    ec2metautils.display(meta, meta.get_meta_data_options(), prefix=True)
  File "/usr/lib/python3.6/site-packages/ec2metadata/ec2metautils.py", line 84, in display
    write_file(sys.stdout, metadata, metaopts, prefix)
  File "/usr/lib/python3.6/site-packages/ec2metadata/ec2metautils.py", line 104, in write_file
    value = metadata.get(metaopt)
  File "/usr/lib/python3.6/site-packages/ec2metadata/__init__.py", line 179, in get
    return self._get(path)
  File "/usr/lib/python3.6/site-packages/ec2metadata/__init__.py", line 102, in _get
    return value.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2024-05-17 14:50:33,925 ERROR: PROBLEM: Issue with ec2metadata output. Check metadata access.

**Comment by rfparedes** [comment]
This error is related to an issue with your instance returning the data from ec2metadata.  You can look into why **ec2metadata --api latest** isn't returning on your instance.  This is most likely the root of all your issues.

susecloud-repocheck needs to handle the error.
